[package]
name = "linksplatform"
version = "0.1.0"
authors = ["photolit"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7.0"
